name: "preprocess"
backend: "python"

input [
    {
        name: "INPUT_IMAGE"
        data_type: TYPE_UINT8
        dims: [-1,-1,-1]
    }
]

output [
    {
        name: "PRE_PROCESSING_IMAGE"
        data_type: TYPE_FP32
        dims: [1,3,640,640]
    },
    {
        name: "PRE_PROCESSING_RATIO"
        data_type: TYPE_FP32
        dims: [2]
    },
    {
        name: "PRE_PROCESSING_DWDH"
        data_type: TYPE_FP32
        dims: [2]
    }
]

instance_group [
    {
        kind: KIND_CPU
    }
]
